config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   # INDEX
   get "tasks", to: 'tasks#index'

   # CREATE
   get "tasks/new", to: 'tasks#new', as: 'new_task'
   post "tasks", to: 'tasks#create'
 
   # SHOW
   get "tasks/:id", to: 'tasks#show', as: 'task'
 
   # UPDATE
   get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
   patch 'tasks/:id', to: 'tasks#update'
 
   # DESTROY
   delete 'tasks/:id', to: 'tasks#destroy'
 
   root to: 'tasks#index'
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]

    def index
      @tasks = Task.all
    end
  
    def show
      # set_restaurant - Substituido pelo before_action
    end
  
    def new
      @task = Task.new
    end
  
    def create
      # Cria um novo restaurante
      @task = Task.new(task_params)
      @task.save
      redirect_to task_path(@task)
    end
  
    def edit
      # set_restaurant - Substituido pelo before_action
    end
  
    def update
      # set_restaurant - Substituido pelo before_action
      @task.update(task_params)
      redirect_to task_path(@task)
    end
  
    def destroy
      @task.destroy
      redirect_to tasks_path
    end
  
    private
  
    def set_task
      @task = Task.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:title, :details, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wikinimous", root_path, class: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'New Article', new_article_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
  <div class='container'>
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :completed %>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <% end %>
  </div>

app/views/tasks/edit.html.erb
<div class="container">
<h1 class = "d-flex justify-content-center">Edit Task</h1>
<br>

<%= render partial: 'form' %>
<div>

app/views/tasks/index.html.erb
<div class="container">
<h1 class = "d-flex justify-content-center">List of Tasks</h1>


<ul class="list-group">
<% @tasks.each do |task| %>
  <li class="list-group-item" ><% if task.completed  %>
  <i class="fas fa-check-square"></i>
  <% else %>
  <i class="far fa-square"></i>
  <% end %>
  <%= link_to task.title, task_path(task) %></li>
<% end %>
</ul>
<br>
<p><%= link_to 'Create Task', new_task_path, class: "btn btn-primary" %></p>

</div>

app/views/tasks/new.html.erb
<h1 class = "d-flex justify-content-center">Create a New Task</h1>
<br>

<%= render partial: 'form' %>

app/views/tasks/show.html.erb
<div class="container">
<h1 class = "d-flex justify-content-center">Info about Task</h1>
<br>
<p><b> Title:     </b><%= @task.title %> </p>
<p><b> Details:   </b><%= @task.details %> </p>
<p><b> Completed: </b><%= @task.completed %> </p>
<br>
<%= link_to 'Edit', edit_task_path(@task), class: "btn btn-primary"   %>

<%= link_to 'Remove', task_path(@task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"  %>

<%= link_to 'Back', tasks_path, class: "btn btn-warning"  %>

<%#= link_to 'Google', 'https://google.com', class: 'link' %>
</div>